.include "include/beatscript.inc"

.section .scene

script script_crazy_cars
    rest 24
    rest 24
    rest 24
    beatscript_cmd 0x07, 0x000000, 0x00000000, 0x00000000
    rest 24
    rest 48
    scene_run crazy_cars_scene_init, 0x00000060
    rest 120
    beatscript_cmd 0x08, 0x000000, 0x00000000, 0x00000000
    rest 24
    rest 96
    stop

@ Scene
struct scene_crazy_cars
    /* Start  */ .word crazy_cars_scene_start, 0
    /* Paused */ .word crazy_cars_scene_pause, 0
    /* Update */ .word crazy_cars_scene_update, 0
    /* Stop   */ .word crazy_cars_scene_stop, 0
    /* Script */ .word script_crazy_cars
endstruct