#pragma once

#include "global.h"

enum StageEnum {
    STAGE_INTRODUCTION = 0,
    STAGE_JIMMY,
    STAGE_9_VOLT,
    STAGE_DRIBBLE,
    STAGE_KAT,
    STAGE_MONA,
    STAGE_DR_CRYGOR,
    STAGE_ORBULON,
    STAGE_WARIO,
    STAGE_JIMMY_REMIX_1,
    STAGE_JIMMY_REMIX_2,
    STAGE_EASY,
    STAGE_THRILLING,
    STAGE_HARD,
    STAGE_TOTAL_BOSS,
    STAGE_SHERIFF,
    STAGE_DR_WARIO,
    STAGE_FLY_SWATTER,
    STAGE_PYORO,
    STAGE_PYORO_2,
    STAGE_JUMP_FOREVER,
    STAGE_PAPER_PLANE,
    STAGE_SKATING_BOARD,
    STAGE_DONG_DONG,
    STAGE_HURDLE,
    STAGE_CHIRITORIE,
    STAGE_CHICKEN_RACE,
    STAGE_STAFF,
    TOTAL_STAGES
};